### ISSUE TITLE
Add ability to undo/redo actions

### ISSUE THREAD

**Issue by jesalynrose** [ServiceNowDevProgram/Menu-Generating-Operations-Program-Widget-Experience-Page#3]
Make sure the page updates the `menuTree`, `menu`, and `outputJSON` client states correctly when [this is added](https://github.com/ServiceNowDevProgram/Menu-Generating-Operations-Program-Widget-Custom-Component/issues/8)

**Comment by ayleeandersen** [comment]
Will you please assign this to me? 😄
